# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 夜猫阿罗哈
subtitle: 暮然回首萧瑟处，也无风雨也无晴
description: 猫老师的个人博客：少儿编程，K12 STEAM 教育，软件开发，项目管理，历史故事等
author: 猫老师
language: zh-CN
timezone: 
keywords: 猫老师少儿编程,少儿编程,编程,K12,STEAM,STEM,JavaScript,NodeJs,历史,PMP,物联网,IoT

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.catxn.net
root: /
permalink: posts/:year/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# include/exclude files/folders
exclude: 
  - "_drafts/*"

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link.enable: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: 杂项
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next
stylus:
  compress: true

# SEO
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# plugins: 
# - hexo-generator-feed

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  - type: git
    message: "hexo deploy to github"
    repo: git@github.com:deltacat/deltacat.github.io.git
    branch: gh-pages
  - type: git
    repo: git@e.coding.net:catxn/catxn.git
    branch: master
    message: "hexo deploy to coding"